spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://0.0.0.0:32768/kotlin-2025?allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=UTC
    username: root
    password: admin213

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
